# Generated by Django 5.2.6 on 2025-09-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_alter_movie_id_alter_mylist_id_alter_myrating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('birth_date', models.DateField(max_length=24)),
            ],
        ),
    ]
