# Generated by Django 5.2.6 on 2025-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actor-images/'),
        ),
    ]
