# Generated by Django 5.2.6 on 2025-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0016_actor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='catogry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
